
development:
  adapter: postgresql
  encoding: unicode
  database: ubermatcher_development
  pool: 5
  username: 
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: ubermatcher_test
  pool: 5
  username: 
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: ubermatcher_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *test