development:
  adapter: sqlite3
  database: db/development.ubermatcher
  pool: 5
  timeout: 5000

test: &test
  adapter: sqlite3
  database: db/test.ubermatcher
  pool: 5
  timeout: 5000

cucumber:
  <<: *test